### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Number while $request->get('limit', 50)

### ISSUE THREAD

**Issue by AlexanderMatveev** [neo4j-documentation/developer-resources#57]
When passing a GET variable (http://localhost:8080/graph?limit=10) to https://github.com/neo4j-contrib/developer-resources/blob/gh-pages/language-guides/php/neo4jphp/index.php#L19, getting this:

> [message] => java.lang.String cannot be cast to java.lang.Number
> [exception] => ClassCastException
> [fullname] => java.lang.ClassCastException

Screenshot: http://screenshare.ru/dlMT0U8f

Just a newbie in neo4j

**Comment by jexp** [comment]
Hey @jadell could you have a look?

**Comment by jadell** [comment]
The issue here is that the limit parameter is being passed from the application to the Neo4j REST server encoded as a JSON string. This is one of the consequences of PHP (a weakly typed language) trying to talk to Java (a strongly typed langauge.) I will submit a pull request for the example code that casts the parameter to an integer before sending it. It is up to @jexp and the rest of the neo4j crew whether they want to do numeric string-to-integer conversions on the server side.

**Comment by AlexanderMatveev** [comment]
@jexp @jadell Thanks!
